# SPDX-License-Identifier: CC-BY-4.0
# Copyright Contributors to the Egeria project.
---
name: Repository
description: Request a new Repository
title: "[REPOSITORY] New Repository"
labels: [repo]
assignees:
  - planetf1
body:
  - type: markdown
    attributes:
      value: |
        Please try and fill in useful information in the form to explain why
        a new repository is needed, and to help get the task moving.
        Come back and update the text in these sections as the discussion progresses,
        or add notes below
  - type: input
    id: reponame
    attributes:
      label: repo-name
      description: |
        What should the repo be called?
        Look at the existing names and try and follow an appropriate pattern, ie egeria-connector-xxx
      placeholder: my-repo-name
      validations:
        required: true
  - type: input
    id: repoowner
    attributes:
      label: Repo Owner
      placeholder: my-github-id
      description: |
        github id(s) of main owner(s)
        This user should be responsible to manage the repo content, handle maintainance tasks like
        dependency updates, security scans, release process.
      validations:
        required: true
  - type: textarea
    id: deliverable
    attributes:
      label: deliverable
      placeholder: |
        Provides an integration connector for magic database X
        Users can use the jar from a build
        Will also publish maven artifacts to maven central, and a container image including base egeria plus this connector
        to quay.io & docker.io
      description: |
        What is the deliverable of this repo, and how will someone use it?
        Are there maven artifacts? Containers? Or something else?
        where will they get them from if not building from source?
      validations:
        required: true
  - type: textarea
    id: build
    attributes:
      label: build
      description: |
        Build & CI/CD process
        How will the new artifacts be built - maven, gradle? scripts?
        What languages are used - Python, Java, Go, .... are particular versions needed?
      validations:
        required: true
  - type: textarea
    id: dependencies
    attributes:
      label: dependencies
      description: |
        Does this depend on other Egeria repos, or them on this? ie for building, testing?
      placeholder: |
        No dependencies directly on other repos
        All egeria dependencies are via maven/gradle.
      validations:
        required: true
  - type: textarea
      id: justification
      attributes:
        label: justification
        description: |
          Why do we need another repo? Were alternatives looked at using existing repos?
        placeholder: |
          Add justification here
        validations:
          required: true
  - type: textarea
      id: assumptions
      attributes:
        label: assumptions
        description: |
          Are all of the following assumptions true? If not please explain why
            - DCO is required
            - Apache 2.0 / CC-BY-4.0 licensed
            - Issue tracking enabled
            - Security scanning will be enabled if possible
            - code scanning will be enabled
            - User docs are in egeria-docs, some technical detailed docs/designs in this repo
            - initial CODEOWNERS will list repository owner primarily
            - Dependabot dependency updates will be set up
            - nominated owner will be responsible for managing the repo content
        validations:
          required: true
  - type: textarea
      id: extra
      attributes:
        label: extra
        description: |
          Any other information?
        placeholder: |
          add any other information here
        validations:
          required: false
