# SPDX-License-Identifier: CC-BY-4.0
# Copyright Contributors to the Egeria project.
---
name: Repository
description: Request a new Repository
title: "[REPOSITORY] New Repository"
labels: [repo]
assignees:
  - planetf1
body:
  - type: markdown
    attributes:
      value: |
        Please try and fill in useful information in the form to explain why a new repository is needed, and to help get the task moving.
        Come back and update the text in these sections as the discussion progresses, or add notes below.
        If you have any ideas on how to improve this form, please open up an issue!
  - type: input
    id: reponame
    attributes:
      label: Name
      description: |
        What should the repo be called?
        Look at the existing names and try and follow an appropriate pattern, ie egeria-connector-xxx
      placeholder: egeria-connector-xxx
    validations:
      required: true
  - type: input
    id: repoowner
    attributes:
      label: Owner
      placeholder: my-github-id
      description: |
        github id(s) of main owner(s)
        This user should be responsible to manage the repo content, handle maintainance tasks like
        dependency updates, security scans, release process. They will be expected to participate in discussions and meetings around release, security as determined by the TSC.
    validations:
      required: true
  - type: textarea
    id: deliverable
    attributes:
      label: Deliverable
      placeholder: |
        Provides an integration connector for magic database X so that metadata on tables and columns can be made available to other cohort members.
      description: |
        What are the deliverables, or outputs, of this repo, and how will someone use them, for what purpose?
    validations:
      required: true
  - type: textarea
    id: build
    attributes:
      label: Build & CI/CD process
      description: |
        How will the deliverables identified above be created & distributed?
        Will maven, gradle (preferred for new repos) be used?
        What languages are used - Python, Java, Go, .... are particular versions needed?
        will a container image be required? 
        What should be checked before a PR can be merged?
        Should javadoc be published?
      placeholder: |
        Provide a very high level overview -- exact details aren't essential at this stage
    validations:
      required: true
  - type: textarea
    id: dependencies
    attributes:
      label: dependencies
      description: |
        Does this depend on other Egeria repos, or them on this? ie for building, testing?
      placeholder: |
        No dependencies directly on other repos
        All egeria dependencies are via maven/gradle.
    validations:
      required: true
  - type: textarea
    id: Justification
    attributes:
      label: justification
      description: |
        Why do we need another repo? Were alternatives looked at using existing repos?
      placeholder: |
        Add justification here
    validations:
      required: true
  - type: textarea
    id: assumptions
    attributes:
      label: Assumptions
      description: |
        Are all of the following assumptions true? If not please explain why
          - DCO is required
          - Apache 2.0 / CC-BY-4.0 licensed
          - Issue tracking enabled
          - Security scanning will be enabled
          - code scanning will be enabled
          - User docs are in egeria-docs, some technical detailed docs/designs in this repo
          - initial CODEOWNERS will list repository owner primarily
          - Dependabot dependency updates will be set up
          - nominated owner will be responsible for managing the repo content
          - repo is public with same group/permissions as the main Egeria repo
          - 
    placeholder: |
      Yes - all true
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Additional Information
      description: |
        Any other information?
        placeholder: |
        add any other information here
    validations:
      required: false
